In [1]:
import pandas as pd
result=pd.read_csv("Image-Classification-and-Price-prediction/scrapping/data/H&M.csv", encoding='utf-8',index_col=False)
print(result.count())
result.head(3)

name           13101
brand          13101
gender         13101
category       13101
size           13101
price          13101
composition    13101
color          13101
url            13101
img_url        13101
article_no     13101
blob_url       13101
dtype: int64


name brand  gender  category   size       price  composition  \
0  3-pack omlottbody   H&M  unisex  babybody  50-74  149,00 kr.  Bomull 100%   
1  3-pack omlottbody   H&M  unisex  babybody  50-74   79,90 kr.  Bomull 100%   
2  3-pack omlottbody   H&M  unisex  babybody  50-74   69,90 kr.  Bomull 100%   

               color                                                url  \
0                Vit  https://www2.hm.com/sv_se/productpage.07017840...   
1  Mörkbeige/Prickig  https://www2.hm.com/sv_se/productpage.07017840...   
2           Gul/Djur  https://www2.hm.com/sv_se/productpage.07017840...   

                                             img_url  article_no  \
0  https://lp2.hm.com/hmgoepprod?set=source[/51/4...   701784001   
1  https://lp2.hm.com/hmgoepprod?set=source[/08/b...   701784002   
2  https://lp2.hm.com/hmgoepprod?set=source[/ba/b...   701784003   

                                            blob_url  
0  https://storage.googleapis.com/urbankiddo/H%26...  
1  https://storage.googleapis.com/urbankiddo/H%26...  
2  https://storage.googleapis.com/urbankiddo/H%26...

In [2]:
result.drop_duplicates().count()

name           13101
brand          13101
gender         13101
category       13101
size           13101
price          13101
composition    13101
color          13101
url            13101
img_url        13101
article_no     13101
blob_url       13101
dtype: int64

In [3]:
df=result
df['category'].unique()


array(['babybody', 'babyscarf', 'blus', 'byxor', 'cardigan', 'halsduk',
       'hatt', 'hårband', 'jacka', 'jumpsuit', 'kjol', 'klänning',
       'leggings', 'mössa', 'overall', 'pannband', 'pufftrosa', 'pyjamas',
       'shorts', 'skjorta', 'skor', 'sovpåse', 'stickad tröja',
       'strumpbyxor', 'strumpor', 't-shirt', 'tofflor', 'topp', 'tröja',
       'vantar', 'väst', 'badbyxor', 'baddräkt', 'dräkt', 'fluga',
       'hängslen', 'jeans', 'kavaj', 'keps', 'väska', 'badtröja',
       'bikinitrosa', 'kappa', 'mockasiner', 'morgonrock', 'trosa',
       'tunika', 'diadem', 'handskar', 'kalsonger', 'kostymväst',
       'leksak', 'långkalsonger', 'maskeradaccessoar', 'skärp',
       'solglasögon', 'benvärmare', 'bikinitopp', 'bolero', 'halsband',
       'hårdekoration', 'hårsnodd', 'hårspänne', 'läppbalsam',
       'nagellack', 'nattlinne', 'pennfodral', 'poncho', 'scarf',
       'ögonmask', 'armband', 'hörlurar', 'simglasögon'], dtype=object)

In [4]:
gr=df.groupby(['category']).count()
#sorting data frame by Team and then By names 
gr.sort_values(["article_no"], axis=0, 
                 ascending=True, inplace=True)

gr['article_no'] = gr['article_no'].astype(int)
gr[gr['article_no']<11]

name  brand  gender  size  price  composition  color  url  \
category                                                                   
armband           1      1       1     1      1            1      1    1   
fluga             1      1       1     1      1            1      1    1   
simglasögon       1      1       1     1      1            1      1    1   
hörlurar          2      2       2     2      2            2      2    2   
mockasiner        2      2       2     2      2            2      2    2   
pannband          2      2       2     2      2            2      2    2   
nagellack         2      2       2     2      2            2      2    2   
badtröja          2      2       2     2      2            2      2    2   
poncho            2      2       2     2      2            2      2    2   
pennfodral        2      2       2     2      2            2      2    2   
kappa             3      3       3     3      3            3      3    3   
hängslen          4      4       4     4      4            4      4    4   
leksak            4      4       4     4      4            4      4    4   
scarf             4      4       4     4      4            4      4    4   
hårdekoration     4      4       4     4      4            4      4    4   
solglasögon       5      5       5     5      5            5      5    5   
läppbalsam        6      6       6     6      6            6      6    6   
handskar          6      6       6     6      6            6      6    6   
ögonmask          6      6       6     6      6            6      6    6   
halsband          6      6       6     6      6            6      6    6   
bikinitopp        6      6       6     6      6            6      6    6   
benvärmare        6      6       6     6      6            6      6    6   
skärp             7      7       7     7      7            7      7    7   
overall           8      8       8     8      8            8      8    8   
tunika            8      8       8     8      8            8      8    8   
långkalsonger     8      8       8     8      8            8      8    8   
bikinitrosa       9      9       9     9      9            9      9    9   

               img_url  article_no  blob_url  
category                                      
armband              1           1         1  
fluga                1           1         1  
simglasögon          1           1         1  
hörlurar             2           2         2  
mockasiner           2           2         2  
pannband             2           2         2  
nagellack            2           2         2  
badtröja             2           2         2  
poncho               2           2         2  
pennfodral           2           2         2  
kappa                3           3         3  
hängslen             4           4         4  
leksak               4           4         4  
scarf                4           4         4  
hårdekoration        4           4         4  
solglasögon          5           5         5  
läppbalsam           6           6         6  
handskar             6           6         6  
ögonmask             6           6         6  
halsband             6           6         6  
bikinitopp           6           6         6  
benvärmare           6           6         6  
skärp                7           7         7  
overall              8           8         8  
tunika               8           8         8  
långkalsonger        8           8         8  
bikinitrosa          9           9         9

In [5]:
df[df['category']=='overall']

name brand  gender category    size       price  \
794          Pilefodrad overall   H&M  unisex  overall   50-74  199,00 kr.   
795          Pilefodrad overall   H&M  unisex  overall   50-74  399,00 kr.   
796          Pilefodrad overall   H&M  unisex  overall   50-74  399,00 kr.   
797       Mönstrad trikåoverall   H&M  unisex  overall   50-74   59,90 kr.   
798       Mönstrad trikåoverall   H&M  unisex  overall   50-74   99,00 kr.   
799       Mönstrad trikåoverall   H&M  unisex  overall   50-74   99,00 kr.   
8342  Vadderad funktionsoverall   H&M    girl  overall  92-140  499,00 kr.   
8343  Vadderad funktionsoverall   H&M    girl  overall  92-140  699,00 kr.   

                composition                     color  \
794             Bomull 100%                   Mörkgrå   
795   Foder: Polyester 100%                 Puderrosa   
796          Polyester 100%                   Mörkblå   
797   Bomull 95%, Viskos 5%  Ljus gråmelerad/Stjärnor   
798             Bomull 100%             Gul/Vitrandig   
799   Bomull 95%, Viskos 5%   Ljus gråmelerad/Blommig   
8342                   Lång                     Svart   
8343                   Lång                 Khakigrön   

                                                    url  \
794   https://www2.hm.com/sv_se/productpage.06602820...   
795   https://www2.hm.com/sv_se/productpage.06900760...   
796   https://www2.hm.com/sv_se/productpage.06900760...   
797   https://www2.hm.com/sv_se/productpage.06245350...   
798   https://www2.hm.com/sv_se/productpage.06245350...   
799   https://www2.hm.com/sv_se/productpage.06245350...   
8342  https://www2.hm.com/sv_se/productpage.06457580...   
8343  https://www2.hm.com/sv_se/productpage.06457580...   

                                                img_url  article_no  \
794   https://lp2.hm.com/hmgoepprod?set=source[/03/b...   660282001   
795   https://lp2.hm.com/hmgoepprod?set=source[/dc/2...   690076001   
796   https://lp2.hm.com/hmgoepprod?set=source[/23/2...   690076002   
797   https://lp2.hm.com/hmgoepprod?set=source[/02/5...   624535001   
798   https://lp2.hm.com/hmgoepprod?set=source[/04/9...   624535002   
799   https://lp2.hm.com/hmgoepprod?set=source[/b2/b...   624535003   
8342  https://lp2.hm.com/hmgoepprod?set=source[/31/6...   645758001   
8343  https://lp2.hm.com/hmgoepprod?set=source[/43/8...   645758002   

                                               blob_url  
794   https://storage.googleapis.com/urbankiddo/H%26...  
795   https://storage.googleapis.com/urbankiddo/H%26...  
796   https://storage.googleapis.com/urbankiddo/H%26...  
797   https://storage.googleapis.com/urbankiddo/H%26...  
798   https://storage.googleapis.com/urbankiddo/H%26...  
799   https://storage.googleapis.com/urbankiddo/H%26...  
8342  https://storage.googleapis.com/urbankiddo/H%26...  
8343  https://storage.googleapis.com/urbankiddo/H%26...

In [6]:
pd.set_option('display.max_colwidth', -1) #full colunm dispaly
df[df['category']=='poncho']
# df=df[df['category']!='poncho']


name brand gender category     size       price  \
8345   Mönstrad poncho  H&M   girl   poncho   92-140   129,00 kr.   
11928  Mönstrad poncho  H&M   girl   poncho   134-170  129,00 kr.   

          composition            color  \
8345   Polyester 100%  Ljusrosa/Ananas   
11928  Polyester 100%  Ljusrosa/Ananas   

                                                         url  \
8345   https://www2.hm.com/sv_se/productpage.0701958001.html   
11928  https://www2.hm.com/sv_se/productpage.0701958001.html   

                                                                                                                                                                                                                  img_url  \
8345   https://lp2.hm.com/hmgoepprod?set=source[/bb/37/bb378b2b24e05864d286da59db3458c422ff7d1d.jpg],origin[dam],category[kids_girl14y_swimwear],type[DESCRIPTIVESTILLLIFE],res[m],hmver[1]&call=url[file:/product/main]+   
11928  https://lp2.hm.com/hmgoepprod?set=source[/bb/37/bb378b2b24e05864d286da59db3458c422ff7d1d.jpg],origin[dam],category[kids_girl14y_swimwear],type[DESCRIPTIVESTILLLIFE],res[m],hmver[1]&call=url[file:/product/main]+   

       article_no                                                    blob_url  
8345   701958001   https://storage.googleapis.com/urbankiddo/H%26M/0701958001  
11928  701958001   https://storage.googleapis.com/urbankiddo/H%26M/0701958001

In [7]:
df['size'].unique()


array(['50-74', '68-104', '92-140', '134-170'], dtype=object)

In [8]:
df['price'].unique()


array(['149,00 kr.', '79,90 kr.', '69,90 kr.', '99,00 kr.', '179,00 kr.',
       '49,90 kr.', '29,90 kr.', '39,90 kr.', '14,90 kr.', '19,90 kr.',
       '249,00 kr.', '59,90 kr.', '129,00 kr.', '199,00 kr.', '89,90 kr.',
       '299,00 kr.', '24,00 kr.', '15,00 kr.', '100,00 kr.', '399,00 kr.',
       '279,00 kr.', '24,90 kr.', '25,00 kr.', '499,00 kr.', '159,00 kr.',
       '229,00 kr.', '349,00 kr.', '11,00 kr.', '49,00 kr.', '119,00 kr.',
       '9,90 kr.', '50,00 kr.', '75,00 kr.', '699,00 kr.', '65,00 kr.',
       '40,00 kr.', '10,00 kr.', '64,00 kr.', '449,00 kr.', '379,00 kr.'],
      dtype=object)

In [9]:
pd.options.display.float_format = '{:,.0f}'.format
df2=df
df2.price=df2.price.str.strip(' kr.')
df2.price=df2.price.str.replace(",",".")

df2['price']=df2['price'].astype(float)
df2['price']=df2['price'].round()
df2['price']=df2['price'].astype(int)

df2.head(2)

name brand  gender  category   size  price  composition  \
0  3-pack omlottbody  H&M   unisex  babybody  50-74  149    Bomull 100%   
1  3-pack omlottbody  H&M   unisex  babybody  50-74  80     Bomull 100%   

               color                                                    url  \
0  Vit                https://www2.hm.com/sv_se/productpage.0701784001.html   
1  Mörkbeige/Prickig  https://www2.hm.com/sv_se/productpage.0701784002.html   

                                                                                                                                                                                                            img_url  \
0  https://lp2.hm.com/hmgoepprod?set=source[/51/45/514519bf74569b4071f87a910bcdb84847068244.jpg],origin[dam],category[],type[DESCRIPTIVESTILLLIFE],res[m],hmver[1]&call=url[file:/product/main]+                      
1  https://lp2.hm.com/hmgoepprod?set=source[/08/be/08be2a1c3e6949fb7865bd2c7080f8edcdffc06e.jpg],origin[dam],category[kids_newborn_bodies],type[DESCRIPTIVESTILLLIFE],res[m],hmver[1]&call=url[file:/product/main]+   

   article_no                                                    blob_url  
0  701784001   https://storage.googleapis.com/urbankiddo/H%26M/0701784001  
1  701784002   https://storage.googleapis.com/urbankiddo/H%26M/0701784002

In [10]:
df2['size'].unique()


array(['50-74', '68-104', '92-140', '134-170'], dtype=object)

In [11]:
colunms=['article_no','gender','category','price','size','brand']
df3=df2[colunms]
df3.head(2)

article_no  gender  category  price   size brand
0  701784001   unisex  babybody  149    50-74  H&M 
1  701784002   unisex  babybody  80     50-74  H&M

In [12]:
df[df['size']=='134-170']['url']

9774     https://www2.hm.com/sv_se/productpage.0497664001.html
9775     https://www2.hm.com/sv_se/productpage.0497664004.html
9776     https://www2.hm.com/sv_se/productpage.0497664006.html
9777     https://www2.hm.com/sv_se/productpage.0497664007.html
9778     https://www2.hm.com/sv_se/productpage.0497664010.html
                                 ...                          
13096    https://www2.hm.com/sv_se/productpage.0670291001.html
13097    https://www2.hm.com/sv_se/productpage.0748815001.html
13098    https://www2.hm.com/sv_se/productpage.0661516001.html
13099    https://www2.hm.com/sv_se/productpage.0717577001.html
13100    https://www2.hm.com/sv_se/productpage.0717577002.html
Name: url, Length: 3327, dtype: object

In [13]:
npr=df3.to_numpy()
npr[0,4]


'50-74'

In [14]:
r,c=npr.shape
print(r,c)

13101 6


In [16]:
import numpy as np
np.zeros([1,c])

array([[0., 0., 0., 0., 0., 0.]])

In [17]:
import numpy as np
npe=np.zeros((1,c))
    
for i in range(r):
    if npr[i,4]=='50-74':
        for s in [44,50,56,62,68,74]:
            npr[i,4]=s
#             print(npr[i,:])
            npe=np.concatenate((npe,npr[i:i+1,:]), axis=0)
    
    if npr[i,4]=='68-104':
        for s in [68,74,80,86,92,98,104]:
            npr[i,4]=s
#             print(npr[i,:])
            npe=np.concatenate((npe,npr[i:i+1,:]), axis=0)
    
    if npr[i,4]=='92-140':
        for s in [92,98,104,110,116,122,128]:
            npr[i,4]=s
    #             print(npr[i,:])
            npe=np.concatenate((npe,npr[i:i+1,:]), axis=0)

    if npr[i,4]=='134-170':
        for s in [134,130,136,152,158,164,170]:
            
            npr[i,4]=s
    #             print(npr[i,:])
            npe=np.concatenate((npe,npr[i:i+1,:]), axis=0)



    


In [18]:
npe[1,:]

array([701784001, 'unisex', 'babybody', 149, 44, 'H&M'], dtype=object)

In [19]:
dfr = pd.DataFrame(npe,columns=['article_no','gender','category','price','new_size','brand'])
dfr = dfr.iloc[1:]
dfr.head(4)

article_no  gender  category price new_size brand
1  701784001  unisex  babybody  149   44       H&M 
2  701784001  unisex  babybody  149   50       H&M 
3  701784001  unisex  babybody  149   56       H&M 
4  701784001  unisex  babybody  149   62       H&M

In [20]:
dfr.to_csv('H&M_cleaned.csv',index=False) #for rows not showing


In [21]:
npe.shape

(90252, 6)

In [22]:
np.concatenate((npe,npr[i:i+1,:]),axis=0)

array([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [701784001, 'unisex', 'babybody', 149, 44, 'H&M'],
       [701784001, 'unisex', 'babybody', 149, 50, 'H&M'],
       ...,
       [717577002, 'girl', 'ögonmask', 40, 164, 'H&M'],
       [717577002, 'girl', 'ögonmask', 40, 170, 'H&M'],
       [717577002, 'girl', 'ögonmask', 40, 170, 'H&M']], dtype=object)

In [23]:
npr[0:1,:]

array([[701784001, 'unisex', 'babybody', 149, 74, 'H&M']], dtype=object)

In [24]:
npr[0]

array([701784001, 'unisex', 'babybody', 149, 74, 'H&M'], dtype=object)

In [25]:
npe.shape

(90252, 6)

In [26]:
npr[i:i+1,:].shape

(1, 6)